import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const interFont = localFont({
  src: [
    {
      path: "/fonts/Inter-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Inter-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-custom"
});

const poppinsFont = localFont({
  src: [
    {
      path: "/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-custom-poppins"
});

export const metadata: Metadata = {
  title: "Kuantta App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.variable} ${interFont.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col md:overflow-hidden">
        {children}
      </body>
    </html>
  );
}
